# Generated by Django 4.1 on 2022-08-23 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="users"
            ),
        ),
    ]
