# Generated by Django 4.1 on 2022-08-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ressource", "0002_remove_ressource_ressourcename_ressource_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressource",
            name="description",
            field=models.CharField(
                help_text="280 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=280,
                null=True,
                verbose_name="description",
            ),
        ),
    ]
