service: authenticaton
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-ifelse
  - serverless-dotenv-plugin

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN

  isOffline: ${env:IS_OFFLINE, "false"}
  serverlessIfElse:
    - If: '"${self:custom.isOffline}" != "true"'
      Exclude:
        - functions.endpoint.handler
      ElseExclude:
        - functions.endpoint.image

provider:
  name: aws
  region: eu-central-1

  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            #- 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::snekauth/*'

  ecr:
    images:
      appimage:
        path: ./

functions:
  endpoint:
    image:
      name: appimage
      command:
        - app.handler
    handler: app.handler
    events:
      - httpApi:
          path: '*'
          method: '*'
